# Generated by Django 5.0.2 on 2024-02-20 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='surname',
            new_name='lastsurname',
        ),
    ]
