# Generated by Django 5.0.2 on 2024-02-22 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_rename_name_user_firstname_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
