# Generated by Django 5.0.2 on 2024-02-22 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image1',
            field=models.ImageField(upload_to='blogs/'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image2',
            field=models.ImageField(upload_to='blogs/'),
        ),
    ]
